# Generated by Django 4.1.1 on 2022-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('assistido', models.BooleanField()),
                ('sexo', models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('documentario', 'Documentário'), ('drama', 'Drama'), ('ficcao', 'Ficção Científica'), ('musica', 'Musical'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('terror', 'Terror')], max_length=15)),
                ('classificacao', models.CharField(choices=[('L', 'Livre'), ('10', '10 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=2)),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
