# Generated by Django 4.1.1 on 2022-10-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_rename_sexo_filme_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='assistido',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='sinopse',
        ),
    ]
