# Generated by Django 4.1.1 on 2022-10-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_remove_filme_assistido_remove_filme_classificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='assistido',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(choices=[('L', 'Livre'), ('10', '10 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('documentario', 'Documentário'), ('drama', 'Drama'), ('ficcao', 'Ficção Científica'), ('musica', 'Musical'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('terror', 'Terror')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
