# Generated by Django 4.1.1 on 2022-10-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_assistido_filme_classificacao_filme_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='assistido',
            field=models.BooleanField(default=False),
        ),
    ]
