# Generated by Django 4.1.1 on 2022-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_alter_filme_assistido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(choices=[('Livre', 'Livre'), ('10', '10 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=5),
        ),
    ]
