# Generated by Django 4.1.1 on 2022-10-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0009_alter_filme_classificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='sinopse',
        ),
    ]
