# Generated by Django 4.1.1 on 2022-10-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0010_remove_filme_sinopse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
    ]
