# Generated by Django 4.1.2 on 2022-11-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_remove_usuario_confirmar_senha'),
        ('filmes', '0015_alter_filme_filme_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='filme_criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.usuario'),
        ),
    ]
