# Generated by Django 4.1.1 on 2022-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmar_senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
