# Generated by Django 4.1.1 on 2022-11-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_usuario_confirmar_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
    ]
