# Generated by Django 4.1.1 on 2022-11-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_remove_usuario_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_senha',
        ),
    ]
